//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyName.Atlas.Contracts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyName.Atlas.Contracts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A presenter view model cannot get accessed its Object property before it&apos;s set. Nulls in Object property are not allowed. So please set it with some value before accessing it..
        /// </summary>
        internal static string APresenterMustHaveAnUnderlyingObject {
            get {
                return ResourceManager.GetString("APresenterMustHaveAnUnderlyingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlas.
        /// </summary>
        internal static string Atlas {
            get {
                return ResourceManager.GetString("Atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion del Usuario Atlas.
        /// </summary>
        internal static string AtlasUserDescription {
            get {
                return ResourceManager.GetString("AtlasUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects implementing ICacheable must implement the interface: &quot;{0}&quot;..
        /// </summary>
        internal static string CacheablesMustImplementContract {
            get {
                return ResourceManager.GetString("CacheablesMustImplementContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede trabajar en las relaciones de entidades que no existan, asegúrese the proveer entidades existentes para relacionar o romper sus relaciones..
        /// </summary>
        internal static string CannotRelateUnrelateNulls {
            get {
                return ResourceManager.GetString("CannotRelateUnrelateNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciembre.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUP.
        /// </summary>
        internal static string DefaultLettersCurrency {
            get {
                return ResourceManager.GetString("DefaultLettersCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string DefaultLettersMeasurementUnit {
            get {
                return ResourceManager.GetString("DefaultLettersMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error cuando se adicionaba el elemento: &quot;{0}&quot;. La causa fue:\n&quot;{1}&quot;..
        /// </summary>
        internal static string ErrorWhileAddingItem {
            get {
                return ResourceManager.GetString("ErrorWhileAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adición fallida.
        /// </summary>
        internal static string ErrorWhileAddingItemTitle {
            get {
                return ResourceManager.GetString("ErrorWhileAddingItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error cuando se eliminaba el elemento: &quot;{0}&quot;. La causa fue:\n&quot;{1}&quot;..
        /// </summary>
        internal static string ErrorWhileDeletingItem {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación fallida.
        /// </summary>
        internal static string ErrorWhileDeletingItemTitle {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given item(s) of the wrong type, the expected type is: &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidTypeOfItem {
            get {
                return ResourceManager.GetString("InvalidTypeOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado exitosamente: &quot;{0}&quot;..
        /// </summary>
        internal static string ItemModified {
            get {
                return ResourceManager.GetString("ItemModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adición fallida de: &quot;{0}&quot;, Se encontraron errores de validación. Estos fueron:.
        /// </summary>
        internal static string ItemNotAddedDueToValidationErrors {
            get {
                return ResourceManager.GetString("ItemNotAddedDueToValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación fallida de: &quot;{0}&quot;, Se encontraron errores de validación. Estos fueron:.
        /// </summary>
        internal static string ItemNotDeletedDueToValidationErrors {
            get {
                return ResourceManager.GetString("ItemNotDeletedDueToValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallos al actualizar: &quot;{0}&quot;..
        /// </summary>
        internal static string ItemNotModified {
            get {
                return ResourceManager.GetString("ItemNotModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización fallida de: &quot;{0}&quot;, Se encontraron errores de validación. Corríjalos y vuelva a intentar..
        /// </summary>
        internal static string ItemNotModifiedDueToValidationErrors {
            get {
                return ResourceManager.GetString("ItemNotModifiedDueToValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juniop.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Usuario Atlas.
        /// </summary>
        internal static string New_AtlasUser {
            get {
                return ResourceManager.GetString("New_AtlasUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Concepto.
        /// </summary>
        internal static string New_SubjectConcept {
            get {
                return ResourceManager.GetString("New_SubjectConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Moneda.
        /// </summary>
        internal static string NewCurrency {
            get {
                return ResourceManager.GetString("NewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion de la Nueva Moneda.
        /// </summary>
        internal static string NewCurrencyDescription {
            get {
                return ResourceManager.GetString("NewCurrencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Configuracion de Reportes.
        /// </summary>
        internal static string NewCustomReportSettings {
            get {
                return ResourceManager.GetString("NewCustomReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion de la Nueva Configuracion de Reportes.
        /// </summary>
        internal static string NewCustomReportSettingsDescription {
            get {
                return ResourceManager.GetString("NewCustomReportSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion del Nuevo Documento.
        /// </summary>
        internal static string NewDocument_Description {
            get {
                return ResourceManager.GetString("NewDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Documento.
        /// </summary>
        internal static string NewDocument_Name {
            get {
                return ResourceManager.GetString("NewDocument_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Acceso (Vacio).
        /// </summary>
        internal static string NewEmptyAccess {
            get {
                return ResourceManager.GetString("NewEmptyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de Nueva Actividad Ejecutada.
        /// </summary>
        internal static string NewExecutedActivityDescription {
            get {
                return ResourceManager.GetString("NewExecutedActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Unidad de Medida.
        /// </summary>
        internal static string NewMeasurementUnit {
            get {
                return ResourceManager.GetString("NewMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion de la Nueva Unidad de Medida.
        /// </summary>
        internal static string NewMeasurementUnitDescription {
            get {
                return ResourceManager.GetString("NewMeasurementUnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Periodo.
        /// </summary>
        internal static string NewPeriod {
            get {
                return ResourceManager.GetString("NewPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Topico.
        /// </summary>
        internal static string NewSubject {
            get {
                return ResourceManager.GetString("NewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion del Nuevo Topico.
        /// </summary>
        internal static string NewSubjectDescription {
            get {
                return ResourceManager.GetString("NewSubjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es requerido..
        /// </summary>
        internal static string NotNullName {
            get {
                return ResourceManager.GetString("NotNullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octuber.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando....
        /// </summary>
        internal static string Proccessing {
            get {
                return ResourceManager.GetString("Proccessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadida exitosamente la Convertible&quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyAddedConvertible {
            get {
                return ResourceManager.GetString("SuccessfullyAddedConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadida exitosamente la Moneda &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyAddedCurrency {
            get {
                return ResourceManager.GetString("SuccessfullyAddedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadido existosamente: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyAddedItemStatusMessage {
            get {
                return ResourceManager.GetString("SuccessfullyAddedItemStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadida exitosamente la Unidad de Medida&quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyAddedMeasurementUnit {
            get {
                return ResourceManager.GetString("SuccessfullyAddedMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado exitosamente el Convertible: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyDeletedConvertible {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminada exitosamente la Moneda: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyDeletedCurrency {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado exitosamente: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyDeletedItemStatusMessage {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedItemStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminada exitosamente la Unidad de Medida: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyDeletedMeasurementUnit {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado exitosamente el Convertible: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyUpdatedConvertible {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizada exitosamente la Moneda: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyUpdatedCurrency {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizada exitosamente la Unidad de Medida: &quot;{0}&quot;..
        /// </summary>
        internal static string SuccessfullyUpdatedMeasurementUnit {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea eliminar el elemento?.
        /// </summary>
        internal static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea eliminar el Convertible: &quot;{0}&quot;?.
        /// </summary>
        internal static string SureToDeleteConvertible {
            get {
                return ResourceManager.GetString("SureToDeleteConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea eliminar la Moneda: &quot;{0}&quot;?.
        /// </summary>
        internal static string SureToDeleteCurrency {
            get {
                return ResourceManager.GetString("SureToDeleteCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea eliminar la Unidad de Medida: &quot;{0}&quot;?.
        /// </summary>
        internal static string SureToDeleteMeasurementUnit {
            get {
                return ResourceManager.GetString("SureToDeleteMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string SureToDeleteTitle {
            get {
                return ResourceManager.GetString("SureToDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un error inesperado ocurrió realizando la operación actual. Los detalles del mismo se han registrado en el log del sistema. Por favor, póngase en contacto con el equipo de soporte y mantenimiento..
        /// </summary>
        internal static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured doing the current operation. The exception details go below:.
        /// </summary>
        internal static string UnexpectedExceptionLogMessage {
            get {
                return ResourceManager.GetString("UnexpectedExceptionLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inesperado.
        /// </summary>
        internal static string UnexpectedExceptionTitle {
            get {
                return ResourceManager.GetString("UnexpectedExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
